nodeLinker: node-modules
npmScopes:
  vpvnguyen:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${{ secrets.NPM_AUTH_TOKEN }}"
