
name: Publish Package

on:
  push:
    branches:
      - main

env:
  node-version: 22

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run:   
          corepack enable yarn
          corepack prepare
          yarn install

      - name: Build package
        run: yarn workspace @yarn-workspace-reference/ui run build

      - name: Publish package
        run: yarn workspace @yarn-workspace-reference/ui npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
