
name: Publish Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

env:
  node-version: 22

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: |
              corepack enable yarn
              corepack prepare
              yarn install

      - name: Build package
        run: yarn workspace @yarn-workspace-reference/ui run build

      - name: Publish package
        run: yarn workspace @yarn-workspace-reference/ui npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
