name: Release and Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://npm.pkg.github.com/"
      - name: Set NODE_AUTH_TOKEN environment variable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: corepack enable yarn
      - run: corepack prepare
      - run: chmod +x ./generate-yarnrc.sh
      - run: ./generate-yarnrc.sh
      - run: echo "NODE_AUTH_TOKEN"
      - run: echo "$NODE_AUTH_TOKEN"
      - run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > "./.npmrc"
      - run: cat ~/.npmrc
      - run: yarn install
      - run: yarn ui:build
      - run: yarn ui:publish
